#!/usr/bin/env tsx

/**
 * Update DefiLlama Protocols List
 *
 * This script fetches the latest protocol data from DefiLlama API
 * and updates the protocols enum file used for intelligent protocol matching.
 *
 * Usage:
 *   npx tsx scripts/update-defillama-protocols.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";
import endent from "endent";

const DEFILLAMA_API_URL = "https://api.llama.fi/protocols";
const OUTPUT_FILE = path.join(
	__dirname,
	"../src/mcp-servers/defillama-mcp/enums/protocols.ts",
);

type DefiLlamaProtocolResponse = {
	id: string;
	name: string;
	address?: string;
	symbol: string;
	url?: string;
	description?: string;
	chain?: string;
	logo?: string;
	audits?: string;
	audit_note?: string;
	gecko_id?: string;
	cmcId?: string;
	category?: string;
	chains?: string[];
	module?: string;
	twitter?: string;
	forkedFrom?: string[];
	oracles?: string[];
	listedAt?: number;
	slug: string;
	tvl?: number;
	chainTvls?: Record<string, number>;
	change_1h?: number;
	change_1d?: number;
	change_7d?: number;
	staking?: number;
	fdv?: number;
	mcap?: number;
};

async function fetchProtocols(): Promise<DefiLlamaProtocolResponse[]> {
	console.log("📡 Fetching protocols from DefiLlama API...");
	const response = await fetch(DEFILLAMA_API_URL);

	if (!response.ok) {
		throw new Error(`Failed to fetch protocols: ${response.statusText}`);
	}

	const protocols = (await response.json()) as DefiLlamaProtocolResponse[];
	console.log(`✅ Fetched ${protocols.length} protocols`);
	return protocols;
}

function generateTypeScriptFile(
	protocols: DefiLlamaProtocolResponse[],
): string {
	const timestamp = new Date().toISOString();

	// Sort protocols by name for easier searching
	const sortedProtocols = protocols.sort((a, b) =>
		a.name.localeCompare(b.name),
	);

	// Map to our simplified structure
	const simplifiedProtocols = sortedProtocols.map((p) => ({
		slug: p.slug,
		name: p.name,
		id: p.id,
		symbol: p.symbol || "-",
	}));

	const protocolsJson = JSON.stringify(simplifiedProtocols, null, "\t");

	return endent`
		/**
		 * DefiLlama Protocols Enum
		 *
		 * This file contains a comprehensive list of all DeFi protocols tracked by DefiLlama.
		 * It is used for intelligent protocol slug matching when users query protocol data.
		 *
		 * Auto-generated by scripts/update-defillama-protocols.ts
		 * Last updated: ${timestamp}
		 * Total protocols: ${protocols.length}
		 */

		export type DefiLlamaProtocol = {
			slug: string;
			name: string;
			id: string;
			symbol: string;
		};

		export const protocols: DefiLlamaProtocol[] = ${protocolsJson};
	`;
}

async function main() {
	try {
		console.log("🚀 Starting DefiLlama protocols update...\n");

		const protocols = await fetchProtocols();

		console.log("📝 Generating TypeScript file...");
		const fileContent = generateTypeScriptFile(protocols);

		const dir = path.dirname(OUTPUT_FILE);
		if (!fs.existsSync(dir)) {
			fs.mkdirSync(dir, { recursive: true });
		}

		fs.writeFileSync(OUTPUT_FILE, fileContent, "utf-8");
		console.log(`✅ Successfully updated ${OUTPUT_FILE}`);

		console.log("\n📊 Statistics:");
		console.log(`   Total protocols: ${protocols.length}`);
	} catch (error) {
		console.error("❌ Error:", error);
		process.exit(1);
	}
}

main();
